### PR TITLE
[bashio] bashio::log instead of echo & Add DEBUG opt [ready merge #3]

### PR DESCRIPTION
**Pull request by baylanger**
As usual if you need any changes don't hesitate.. I did this kind of "fast" , time for diner :)

### CODE REVIEW

**Comment by baylanger** [comment]
I added the debug option so it can be configured in the UI - in Python that's easy to set the logging.  It seems bashio most likely automatically handle this option - otherwise we'd need to use something like:
```
if bashio::config.true debug; then
 ...
```

**Comment by baylanger** [comment]
Ready to merge.

Note: Even with the added option DEBUG, bashio::log.debug doesn't work :(   log.debug was used only for this (so far):

```
Connecting to MQTT server; subscribe topics tesla_ble/+ and homeassistant/status
```

I vote to merge this unless you see anything.

**Comment by baylanger** [comment]
First merge #12 otherwise there will be conflict.

**Comment by raphmur** [comment]
I like your bashio logging. However, this interferes with the possibility to run this as standalone.
I will merge and create a helper function that will switch between bashio & echo

**Comment by baylanger** [comment]
> I like your bashio logging. However, this interferes with the possibility to run this as standalone. I will merge and create a helper function that will switch between bashio & echo

🎉🎉🎉

If you don’t have the time before going to bed to do the helper function, I’ll do it. I somehow thought about this as well for easier testing.

**Comment by raphmur** [comment]
Feel free. Don't loose your energy :)
Tu peux te joindre sur ce discord: https://discord.com/invite/zkZktGFk ça permettra au moins de partager des emails si nécessaire

**Pull request merged**
